# Generated by Django 3.1.3 on 2020-11-28 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 28, 12, 47, 9, 677538, tzinfo=utc)),
        ),
    ]
