# Generated by Django 3.1.3 on 2020-11-22 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=2, max_length=1)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=4, max_length=4)),
                ('image_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('image5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('image6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
